### PR TITLE
Update something

### PR DESCRIPTION
**Pull request by realdennis**
- **Dependency a temporary arpjs (work around for node v10)** 
(cause node_pcap and socketwatcher some namespace error in v10?) 
watch [this](https://github.com/node-pcap/node_pcap/issues/242) and [this](https://github.com/node-pcap/node_pcap/pull/243/commits/71ecb068107b36dd8addbd670930f5b4f0befd5e)

- Remove broken badge (bitHound)
- Add greenkeeper and remove nsp to keep the dependencies newest and safe
- Add osx enviroment for travis
- Some code style change for standard latest version auto fix

### CODE REVIEW

**Comment by roccomuso** [comment]
@realdennis does it works for you after the merge?

**Comment by realdennis** [comment]
Hey, I thought the root cause about Node v10 is the **node_pcap**(namespace error & depend old socketwatcher) but it fixed after merge [243](https://github.com/node-pcap/node_pcap/pull/243)

In this repo's(kickthemout) pull request, I just remove broken badge, update some dependencies and add Greenkeeper(but you need to open it). 

Greenkeeper continuous check project's dependencies version and tell you CI result.
(You can merge it when build pass.) Like [this](https://github.com/lukechilds/reverse-shell/pull/16).

By the way, I thought we need to write more test case to keep a robust CI not just check coding style.

**Comment by roccomuso** [comment]
Yeah, PRs are welcome. I had no time to write tests.

Btw right now the inquirer selection is stuck when i run it with node 8. Are you having the same issue?

**Comment by realdennis** [comment]
I don't have this issue in Node v8, but I found [that](https://github.com/SBoudrias/Inquirer.js) Inquirer.js doesn't support  version under Node v6, I am sorry to aware it too late.

**Pull request merged**
